"""P01-T05: build data/intelligence/technique_registry.yaml from reg_parts/*.txt.

Pipe-separated rows: id|name|owner_code|module|phases|pipelines|model|cost|net
"""
from __future__ import annotations

import os
from collections import OrderedDict

BASE = os.path.dirname(os.path.abspath(__file__))
OWNER = {"IIE": "CRIBA_IIE", "CR": "CRIBA", "CSI": "CRIBA_PLUS_IIE", "SUPRA": "SUPRA_ORCHESTRATION"}
FAMILY = {  # by id range, addendum sections 87-94
    (1, 9): "PATENT_INTELLIGENCE", (10, 30): "EXTERNAL_SOURCES",
    (31, 45): "RETRIEVAL_GRAPH", (46, 52): "TOPIC_DYNAMICS",
    (53, 79): "INVENTION", (80, 95): "NOVELTY_KNOWLEDGE_GRAPH",
    (96, 115): "SIGNALS_EVIDENCE_OPPORTUNITY", (116, 130): "ADVERSARIAL_FUTURES",
}
SUBS = {
    "T126": ["unmet needs", "review mining", "workaround mining", "workflow friction"],
    "T127": ["human bottleneck", "API unlock", "hardware unlock", "dataset unlock", "model unlock", "open-source unlock"],
    "T128": ["patent expiration", "abandoned IP", "dormant papers", "sleeping beauties"],
    "T129": ["second-order effects", "N-th-order effects", "counterfactual", "future-back", "bottleneck mapping"],
    "T130": ["S-curve detection", "substitution curves", "innovation genealogy"],
}

# Phase-owned capability metadata.  This generator is the single writable
# source for technique_registry.yaml; techniques absent here remain PLANNED.
# VACIO desde 2026-09-07 (correccion de integridad): el commit cbac469
# ("remove never-activated engine modules ~5.1k lines") elimino los modulos
# invention/* y sus tests, pero el registro siguio declarando 11 tecnicas
# IMPLEMENTED sobre codigo borrado. Vuelven a PLANNED hasta re-implementacion
# real; todo override futuro debe citar el commit que introduce el modulo y
# sus tests deben existir en tests/ (verificado por
# tests/intelligence/test_technique_runtime_traceability.py).
IMPLEMENTATION_OVERRIDES: dict[str, dict] = {}

def family_of(tid: str) -> str:
    n = int(tid[1:])
    for (a, b), fam in FAMILY.items():
        if a <= n <= b:
            return fam
    raise ValueError(tid)

def slug(name: str) -> str:
    keep = "abcdefghijklmnopqrstuvwxyz0123456789"
    return "".join(c if c in keep else "_" for c in name.lower()).strip("_")[:48]

def yq(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

rows = OrderedDict()
for part in ("p1", "p2", "p3", "p4"):
    with open(os.path.join(BASE, "reg_parts", f"{part}.txt"), encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            fields = line.split("|")
            assert len(fields) == 9, f"{part}: {len(fields)} fields in {fields[0]}"
            rows[fields[0]] = fields

ids = list(rows)
expected = [f"T{i:03d}" for i in range(1, 131)]
missing = [t for t in expected if t not in rows]
extra = [t for t in ids if t not in expected]
if missing or extra:
    raise SystemExit(f"MISSING={missing} EXTRA={extra}")

CANON_VERSION = "2026-09-07.2"  # bump when reg_parts/*.txt or overrides change

out = [
    "# CRIBA IIE technique registry - T001-T130 (GENERATED by gen_registry.py; do not edit by hand)",
    "",
    "schema_version: 2",
    f"canon_version: {yq(CANON_VERSION)}",
    "provenance:",
    "  source: \"ADDENDUM 'INTEGRACION EXHAUSTIVA DE LAS 130 TECNICAS' secciones 87-94\"",
    "  generator: .hermes/iie/gen_registry.py",
    "  parts:",
] + [f"    - .hermes/iie/reg_parts/{part}.txt" for part in ("p1", "p2", "p3", "p4")]
out += ["techniques:", ""]
for tid, f in rows.items():
    rid, name, oc, module, phases, pipelines, model, cost, net = f
    override = IMPLEMENTATION_OVERRIDES.get(tid, {})
    status = "IMPLEMENTED" if override else "PLANNED"
    implementation = override.get("implementation")
    input_contracts = override.get("input_contracts", [])
    output_contracts = override.get("output_contracts", [])
    tests = override.get("tests", [f"test_{rid.lower()}_{slug(name)}"])
    out += [
        f"- id: {rid}",
        f"  name: {yq(name)}",
        f"  family: {family_of(tid)}",
        f"  owner: {OWNER[oc]}",
        "  module:",
    ]
    out += [f"    - criba.intelligence.{m}" for m in module.replace(" ", "").split("+")]
    out += ["  phase:"] + [f"    - {p}" for p in phases.split("+")]
    out += ["  pipelines:"] + [f"    - {p}" for p in pipelines.replace(" ", "").split("+")]
    out += [
        "  model:",
        "    default: GLM-5.3",
        f"    reasoning: {model.replace('lowhigh', 'low|high')}",
        f"  cost_class: {cost}",
        f"  requires_network: {'true' if net == '1' else 'false'}",
        "  requires_credentials: false",
        f"  status: {status}",
        f"  implementation: {yq(implementation) if implementation else 'null'}",
    ]
    for field, values, quote_values in (
        ("input_contracts", input_contracts, True),
        ("output_contracts", output_contracts, True),
        ("tests", tests, False),
    ):
        if not values:
            out.append(f"  {field}: []")
            continue
        out.append(f"  {field}:")
        out += [f"    - {yq(value) if quote_values else value}" for value in values]
    if tid in SUBS:
        out.append("  subtechniques:")
        out += [f"    - {yq(s)}" for s in SUBS[tid]]
    out.append("")

# Derive the destination from BASE (repo checkout or portable bundle): this
# script reads reg_parts/ relative to itself, so it must also write relative
# to itself instead of a hardcoded absolute path (qa P2-3).
dest = os.path.normpath(os.path.join(
    BASE, "..", "..", "data", "intelligence", "technique_registry.yaml"))
os.makedirs(os.path.dirname(dest), exist_ok=True)
with open(dest, "w", encoding="utf-8") as fh:
    fh.write("\n".join(out) + "\n")
print(f"OK: {len(rows)} techniques -> {dest}")
