"""Condition 15 — real v1 MANDATORY_MODEL_PACKET regression.

Loads a REAL v1 packet (tests/fixtures/mandatory_model_packet_v1.json generated by
the legacy engine), migrates to v2 without error, preserves legacy fields, adds
schema_version 2.0.0 and the innovation block (empty or safely migrated).
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "src"))

from criba import engine
from criba.migration import migrate_v1_to_v2

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "mandatory_model_packet_v1.json")


def _load():
    with open(FIXTURE, encoding="utf-8") as f:
        return json.load(f)


def test_fixture_is_real_v1():
    v1 = _load()
    assert v1.get("packet_type") == "MANDATORY_MODEL_PACKET"
    assert "ideas" in v1 and len(v1["ideas"]) >= 1


def test_migration_no_exception_and_schema():
    v1 = _load()
    v2 = migrate_v1_to_v2(v1)
    assert v2["schema_version"] == "2.0.0"


def test_legacy_fields_preserved():
    v1 = _load()
    v2 = migrate_v1_to_v2(v1)
    for f in ("selected_current", "supporting_methods", "contextualization", "rupture",
              "experiment", "decision", "model_instruction", "response_contract"):
        assert f in v2, f"campo legacy perdido: {f}"
    assert v2["original_query"] == v1["original_query"]
    assert v2["decision"]["recommended_status"] == v1["decision"]["recommended_status"]
    assert v2["activation_id"] == v1["activation_id"]


def test_innovation_block_added():
    v2 = migrate_v1_to_v2(_load())
    inv = v2["innovation"]
    for k in ("known_space", "saturated_mechanisms", "assumptions", "ruptures",
              "idea_families", "ideas", "duplicate_report", "unclassified_properties"):
        assert k in inv, f"falta {k} en innovation"
    assert "migration" in inv
    assert inv["migration"]["source_schema_version"].startswith("1")
    # ruptures may be empty if v1 had no operations; that's valid (not fabricated)
    assert isinstance(inv["ruptures"], list)


def test_no_fabricated_content():
    v1 = _load()
    v2 = migrate_v1_to_v2(v1)
    # count preserved (v1 ideas had no id; migration assigns LEGxx)
    n_v1 = len(v1["ideas"])
    n_v2 = len(v2["innovation"]["ideas"])
    assert n_v2 == n_v1, "no debe inventar ni perder ideas"
    # genomes incomplete -> all unknown, never declared classified
    for i in v2["innovation"]["ideas"]:
        assert i["duplicate_status"] == "migrated_incomplete"
        g = i["genome"]
        assert all(g[f] == ["unknown"] for f in ("actor", "mechanism", "topology", "trust_model", "time_model"))


def test_legacy_alias_same_object():
    v2 = migrate_v1_to_v2(_load())
    assert v2["ideas"] is v2["innovation"]["ideas"]


def test_reopen_and_prompt_and_serialize():
    v2 = migrate_v1_to_v2(_load())
    # serialize
    blob = json.dumps(v2, ensure_ascii=False)
    back = json.loads(blob)
    assert back["schema_version"] == "2.0.0"
    # prompt builds
    out = engine.build_prompt(v2)
    assert "MANDATORY_MODEL_PACKET" in out
